### PR TITLE
Avoid to use jest-get-type in production

### PR DESCRIPTION
**Pull request by valse**
Hi,
   I removed the jest-get-type dependency because this library is not for production build.

Compiling it in my web app project breaks the compatibility with IE11 and old Chrome (like 41).

Thanks
Marco

### CODE REVIEW

**Comment by slorenzo** [comment]
I think this PR should be merge, ` jest-get-type` breaks the build process at least in [CRA](https://github.com/facebook/create-react-app).

**Comment by mvasin** [comment]
@slorenzo Thanks for sharing the issue, Sebastián, however I was not able to reproduce build failure. wI did `npx create-react-app app && cd app && npx add react-div-100vh`. Then I used this code in `App.js`:
```jsx
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Div100vh from 'react-div-100vh'

class App extends Component {
  render() {
    return (
      <Div100vh className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </Div100vh>
    );
  }
}

export default App;
```

It builds fine with both `npm run start` and `npm run build` for me. What sequence of commands make CRA build fail in your case?

Regarding the merge, I'm currently exploring the options there are to test the component automatically in IE11. It's very tempting to just fix bugs ad-hoc, but I believe it's beneficial for the long-term code quality to fix issues in TDD style. So wait a bit or share your ideas on how to write a failing test for the issue that this PR will fix.

**Comment by mvasin** [comment]
I came up with a script that highlights the issue: https://gist.github.com/mvasin/ec57d4ada383c8a467c1cafc1ebfe435; it does fail in IE11 and does success in the latest Chrome.

Now I need to integrate that into the CI pipeline, in other words to make it run on CircleCI on every commit, and I'd love to have some help with that.

**Comment by theaklair** [comment]
Encountered the same issue with IE browser.
But I see it's been a while since any updates on that issue.
It's sad but it seems that I have to fork your package, and then maybe return to the original when current PR is merged.

**Comment by mvasin** [comment]
Hey @theaklair, I’m glad you find this component useful. I’ll handle this PR within 3 days, either will add tests first and then will merge or will just merge it as is.

**Pull request merged**
